server:
   port: 8081
   servlet:
     jsp:
       init-parameters:
         development: true

logging:
  level:
    root: INFO
    com.lic.aop: DEBUG

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yx?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.lic.entity
